"""new

Revision ID: 1b32cf563588
Revises: e3115c3e60d6
Create Date: 2025-02-23 03:43:35.810076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b32cf563588'
down_revision = 'e3115c3e60d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('title_ar', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('description_ar', sa.Text(), nullable=True))
    op.add_column('anime', sa.Column('synonyms_ar', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('status_ar', sa.String(length=50), nullable=True))
    op.add_column('anime', sa.Column('genres_ar', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('studios_ar', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('producers_ar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'producers_ar')
    op.drop_column('anime', 'studios_ar')
    op.drop_column('anime', 'genres_ar')
    op.drop_column('anime', 'status_ar')
    op.drop_column('anime', 'synonyms_ar')
    op.drop_column('anime', 'description_ar')
    op.drop_column('anime', 'title_ar')
    # ### end Alembic commands ###
