"""empty message

Revision ID: 68a52b4b7caa
Revises: 
Create Date: 2025-02-12 04:41:17.958166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a52b4b7caa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.String(length=10), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('season_count', sa.Integer(), nullable=True),
    sa.Column('special_episode_count', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('japanese_title', sa.String(length=255), nullable=True),
    sa.Column('synonyms', sa.String(length=255), nullable=True),
    sa.Column('aired', sa.String(length=255), nullable=True),
    sa.Column('premiered', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('mal_score', sa.Float(), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('studios', sa.String(length=255), nullable=True),
    sa.Column('producers', sa.String(length=255), nullable=True),
    sa.Column('poster_image', sa.String(length=255), nullable=True),
    sa.Column('portrait_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('anime')
    # ### end Alembic commands ###
