"""Add profile_picture and role columns to user model

Revision ID: 8762546d5ca2
Revises: 68a52b4b7caa
Create Date: 2025-02-14 21:11:05.488157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8762546d5ca2'
down_revision = '68a52b4b7caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('anime', 'season_count')
    #op.drop_column('anime', 'special_episode_count')
    #op.add_column('user', sa.Column('profile_picture', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'profile_picture')
    op.add_column('anime', sa.Column('special_episode_count', sa.INTEGER(), nullable=True))
    op.add_column('anime', sa.Column('season_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
