"""new1

Revision ID: 8ae36b613112
Revises: 1b32cf563588
Create Date: 2025-02-23 05:11:12.088487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae36b613112'
down_revision = '1b32cf563588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('rating_ar', sa.String(length=50), nullable=True))
    op.add_column('anime', sa.Column('type_ar', sa.String(length=50), nullable=True))
    op.add_column('anime', sa.Column('duration_ar', sa.String(length=50), nullable=True))
    op.add_column('anime', sa.Column('aired_ar', sa.String(length=255), nullable=True))
    op.add_column('anime', sa.Column('premiered_ar', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'premiered_ar')
    op.drop_column('anime', 'aired_ar')
    op.drop_column('anime', 'duration_ar')
    op.drop_column('anime', 'type_ar')
    op.drop_column('anime', 'rating_ar')
    # ### end Alembic commands ###
