"""new2

Revision ID: 8e9948f65791
Revises: 8ae36b613112
Create Date: 2025-02-23 05:23:15.199530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9948f65791'
down_revision = '8ae36b613112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'title_ar')
    op.drop_column('anime', 'studios_ar')
    op.drop_column('anime', 'producers_ar')
    op.drop_column('anime', 'synonyms_ar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('synonyms_ar', sa.VARCHAR(length=255), nullable=True))
    op.add_column('anime', sa.Column('producers_ar', sa.VARCHAR(length=255), nullable=True))
    op.add_column('anime', sa.Column('studios_ar', sa.VARCHAR(length=255), nullable=True))
    op.add_column('anime', sa.Column('title_ar', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
