"""Add mal_code column to Anime model

Revision ID: 8f81a5cef6f8
Revises: 8762546d5ca2
Create Date: 2025-02-15 20:29:58.077603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f81a5cef6f8'
down_revision = '8762546d5ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('episode_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_embed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('anime', sa.Column('mal_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'mal_code')
    op.drop_table('episode_embed')
    op.drop_table('episode')
    # ### end Alembic commands ###
