"""skibiditoilet

Revision ID: e3115c3e60d6
Revises: d9fc4fcb694b
Create Date: 2025-02-15 22:22:11.684717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3115c3e60d6'
down_revision = 'd9fc4fcb694b'
branch_labels = None
depends_on = None


def upgrade():
    # Create the new table as before
    op.create_table(
        'comment_vote',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('vote', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['comment_id'], ['comment.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'comment_id', name='_user_comment_uc')
    )

    # Use batch mode to add the foreign key constraint on the "comment" table.
    with op.batch_alter_table('comment') as batch_op:
        batch_op.create_foreign_key('fk_comment_parent', 'comment', ['parent_id'], ['id'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_table('comment_vote')
    # ### end Alembic commands ###
