"""spot

Revision ID: f32ebabed325
Revises: 4814bca9a7cd
Create Date: 2025-03-02 10:10:59.580693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32ebabed325'
down_revision = '4814bca9a7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_vote', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_vote', 'timestamp')
    # ### end Alembic commands ###
